In [4]:
import pandas as pd
import numpy as np
import sys

sys.path.append("../scripts")   # path from notebook → per10.py folder
sys.path.append("../processed")

from per10 import (
    compute_improv_score,
    compute_all_improv
)

In [6]:
df = pd.read_csv("../processed/input_cleaned_w1_2_3.csv")
df.head()

,game_id,play_id,nfl_id,frame_id,player_position,player_side,player_role,x,y,s,...,season,week,pass_result,pass_length,route_of_targeted_receiver,team_coverage_man_zone,yards_gained,expected_points,expected_points_added,throw_frame
0,2023090700,101,52546,16,CB,Defense,Defensive Coverage,46.73,12.92,3.17,...,2023,1,I,22,CORNER,ZONE_COVERAGE,0,0.927021,-2.145443,26
1,2023090700,101,52546,17,CB,Defense,Defensive Coverage,47.02,13.03,3.09,...,2023,1,I,22,CORNER,ZONE_COVERAGE,0,0.927021,-2.145443,26
2,2023090700,101,52546,18,CB,Defense,Defensive Coverage,47.27,13.12,2.77,...,2023,1,I,22,CORNER,ZONE_COVERAGE,0,0.927021,-2.145443,26
3,2023090700,101,52546,19,CB,Defense,Defensive Coverage,47.51,13.19,2.39,...,2023,1,I,22,CORNER,ZONE_COVERAGE,0,0.927021,-2.145443,26
4,2023090700,101,52546,20,CB,Defense,Defensive Coverage,47.73,13.23,2.03,...,2023,1,I,22,CORNER,ZONE_COVERAGE,0,0.927021,-2.145443,26

In [7]:
sample_play_ids = df["play_id"].drop_duplicates().sample(n=15, random_state=42)
sample_df = df[df["play_id"].isin(sample_play_ids)]

In [12]:
improv_results = compute_all_improv(sample_df)
improv_results.head(10)

   play_id  nfl_id  improv_score
0      147   56045          2.95
1      147   53565          2.67
2      147   53511          2.64
3      147   47859          2.14
4      147   54481          2.26
5      383   52469          2.74
6      383   54500          1.87
7      383   47822          1.72
8      383   54476          2.79
9      383   55133          2.69

In [13]:
improv_results["improv_score"].describe()

count    93.000000
mean      3.165269
std       0.772128
min       1.260000
25%       2.760000
50%       3.010000
75%       3.330000
max       5.450000
Name: improv_score, dtype: float64

In [14]:
improv_results.groupby("play_id")["improv_score"].mean()

play_id
147     2.532000
383     2.513333
841     3.395000
1096    3.317778
1632    3.335000
1645    3.300000
1720    3.175000
1744    2.953333
2041    2.806667
2292    3.046667
2768    3.566000
3311    2.554000
3475    3.088000
3994    4.204000
4134    3.408462
Name: improv_score, dtype: float64